query RunsQuery (
  $pipelineName: String!
){
  pipelineRunsOrError(filter:{
    pipelineName: $pipelineName
  }) {
    ... on PipelineRuns{
      count
      results{
        pipelineName
        runId
        runConfig
        status
        tags{
          key
          value
        }
        updateTime
        startTime
        endTime
      }
    }
  }
}