query LogQuery(
  $runId: ID!
)
{
  logsForRun(runId: $runId){
    ... on EventConnection{
      events{
        ... on LogMessageEvent{
          message
          timestamp
          stepKey
        }
        ... on LogsCapturedEvent{
          message
          timestamp
          stepKey
        }
      }
    }
  }
}