version: 1.0.0
name: cloud manifest production github
apps:
  - uuid: a97f6b42-4988-11f1-ab98-f74a5cd6d7bb
    release: latest
workflows:
  - uuid: 4be1a58a-a45a-4657-98b1-51985c4ef6dd
    release: latest
  - uuid: 5a2c7f4f-5f3b-4471-8322-2b9b783decc9
    release: latest
  - uuid: 99ce804a-4f49-4d2d-855f-e8aef27f575d
    release: latest
